#!/sbin/runscript
# Gentoo init script for Overwatch
# Copyright (C) 2015, Overwatch Inc.
# by gentuxx <gentuxx@gmail.com>

opts="${opts} status configtest"

WAZUH_HOME=WAZUH_HOME_TMP
WAZUH_CONTROL="$WAZUH_HOME/bin/wazuh-control"

depend() {
    need net
    use logger
}

configtest() {
    ebegin "Checking Overwatch Configuration"
    checkconfig
    eend $?
}

checkconfig() {
    CONFIGFILE="${CONFIGFILE:-$WAZUH_HOME/etc/ossec.conf}"
    if [ ! -r "${CONFIGFILE}" ]; then
        eerror "Unable to read configuration file: ${CONFIGFILE}"
        return 1
    fi

    # Maybe put some kind of config file syntax checking in here?  XML is a little different
    # so maybe not.
    return $ret
}

start() {
    checkconfig || return 1
    ebegin "Starting Overwatch"
    ${WAZUH_CONTROL} start > /dev/null 2>&1
    eend $?
}

stop() {
    checkconfig || return 1
    ebegin "Stopping Overwatch"
    ${WAZUH_CONTROL} stop > /dev/null 2>&1
    eend $?
}

restart() {
    if ! service_started "${myservice}" ; then
        eerror "Overwatch is not running! Please start it before trying to reload it."
    else
        checkconfig || return 1
        ebegin "Reloading Overwatch"
        svc_stop ${WAZUH_CONTROL}
        svc_start ${WAZUH_CONTROL}
        eend $?
    fi
}

status() {
    checkconfig || return 1
    ${WAZUH_CONTROL} status
}
